stages:
  - build

build_latest:
  tags:
    - dind
  stage: build
  services:
    - docker:dind
  variables:
    IMAGE: $CI_REGISTRY/$IMAGE_NAME
  script:
    - echo $CI_REGISTRY
    - echo $IMAGE_NAME
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE .
    - docker tag $IMAGE $IMAGE:latest
    - docker tag $IMAGE $IMAGE:$CI_COMMIT_REF_SLUG
    - docker push $IMAGE
  only:
    refs:
      -  /^[0-9]*\.[0-9]*\.[0-9]*$/